server:
  servlet:
    context-path: /gestao-funcionarios/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
      driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
